export default interface ThemeInterface {
    bgColor: string;
    textColor: string;
    textColorSecondary: string;
    filterListBg: string;
    filterCheck: string;
    invoiceBg: string;
    invoiceBgSecondary: string;
    totalBlockBg: string;
    editBtnBg: string;
    editBtnColor: string;
    formBg: string;
    inputBorder: string;
    selectOptionBg: string;
    selectOptBorder: string;
    selectOptHover: string;
    selectOptBoxShadow?: string;
    selectItemListText: string;
    selectTopWrapperBg: string;
    backLinkHover: string;
    deleteBtnBg: string;
    general: {
        iconColor: string;
        purple: string;
        purpleLight: string;
        greenBg: string;
        greenLight: string;
        headerBg: string;
        headerBorder: string;
        orangeBg: string;
        orangeLight: string;
        gray: string;
        white: string;
        black: string;
        uidHash: string;
        deleteBtnBg: string;
        markBtnBg: string;
    }
}